import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

# Mapea Command + Left para mover una palabra hacia la izquierda
[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001Bb"

# Mapea Command + Right para mover una palabra hacia la derecha
[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001Bf"

# Desactivo Command + UP/Down
[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = ""

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = ""

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000c"
key = "L"
mods = "Control"

# TMUX PANE RISIZE
[[keyboard.bindings]]
key = "Up"
mods = "Control|Alt"
chars = "\u0002\u001b[1;5A"

[[keyboard.bindings]]
key = "Down"
mods = "Control|Alt"
chars = "\u0002\u001b[1;5B"

[[keyboard.bindings]]
key = "Left"
mods = "Control|Alt"
chars = "\u0002\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Control|Alt"
chars = "\u0002\u001b[1;5C"


[scrolling]
history = 100000
multiplier = 2

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
opacity = 0.9
blur = true
title = "Alacritty"
decorations = "Buttonless"

[selection]
save_to_clipboard = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[window.dimensions]
lines = 48
columns = 160

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
#program = "/usr/local/bin/fish"
program = "/bin/zsh"
