import = [
   "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "VictorMonoNF Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMonoNF Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMonoNF Nerd Font"
style = "Regular"

[font.normal]
family = "VictorMonoNF Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0


# Ctrl + Flecha Derecha (Avanzar palabra)
[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

# Ctrl + Flecha Izquierda (Retroceder palabra)
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000c"
key = "L"
mods = "Control"

# TMUX SELECT PANE
[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u0002\u001b[1;5A"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u0002\u001b[1;5B"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0002\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0002\u001b[1;5C"

# TMUX RESIZE PANE
[[keyboard.bindings]]
key = "Up"
mods = "Command|Shift"
chars = "\u0002\u001b[1;3A"

[[keyboard.bindings]]
key = "Down"
mods = "Command|Shift"
chars = "\u0002\u001b[1;3B"

[[keyboard.bindings]]
key = "Left"
mods = "Command|Shift"
chars = "\u0002\u001b[1;3D"

[[keyboard.bindings]]
key = "Right"
mods = "Command|Shift"
chars = "\u0002\u001b[1;3C"


[scrolling]
history = 100000
multiplier = 2

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
opacity = 0.8
blur = true
title = "Alacritty"
decorations = "Buttonless"

[selection]
save_to_clipboard = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[window.dimensions]
lines = 48
columns = 160

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"
